# -*- coding: utf-8 -*-
"""FTF_GraphRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB3M3SptL994gRKnYhzSSwi60-f_5Qvx
"""

!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

# URL of the website to scrape
url = 'https://fitnesstravelfood.com/seven-sisters-hill-the-best-trek-near-nagpur/'

# Send a GET request to the URL
response = requests.get(url)

# Parse the HTML content of the page
soup = BeautifulSoup(response.content, 'html.parser')

# Find all paragraph tags
paragraphs = soup.find_all('p')

# Extract text from each paragraph
text_data = [para.get_text() for para in paragraphs]

text_data

# Define the filename
filename = 'scraped_data.txt'

# Open the file in write mode and ensure proper encoding
with open(filename, 'w', encoding='utf-8') as file:
    for line in text_data:
        file.write(line + '\n')

print(f"Data has been saved to {filename}")

